### PR TITLE
Adding priority labels to tasks in addition to colors

### PR DESCRIPTION
**Pull request by asakura42**
+ small code block for saving on exit

### CODE REVIEW

**Comment by lewis-weinberger** [comment]
Thanks @asakura42. I think both save-on-exit and priority labels are good new features! However I'm not sure I'd want to make them the default though. Would it be possible to add some configuration options for these, so that users can toggle them on if they want them?

**Comment by asakura42** [comment]
@lewis-weinberger
>Would it be possible to add some configuration options for these, so that users can toggle them on if they want them?

Honestly I'm bad in Rust (totally newbie heh). So I'll try to implement it but without any guarantee. Maybe you know how to do it properly?

**Comment by lewis-weinberger** [comment]
> Honestly I'm bad in Rust (totally newbie heh). So I'll try to implement it but without any guarantee. Maybe you know how to do it properly?

I can help along the way! 

The place to start is to edit the `Config` struct defined in [config.rs](https://github.com/lewis-weinberger/yat-rs/blob/master/src/config.rs) to add the new boolean options (e.g. `save_on_exit` and `print_priority`). The `Window` struct defined in [tui.rs](https://github.com/lewis-weinberger/yat-rs/blob/master/src/tui.rs) keeps track of that config, and the `View` struct defined in [lib.rs](https://github.com/lewis-weinberger/yat-rs/blob/master/src/lib.rs) keeps track of that window. So by editing the `Config` struct you'll have access to those options in the `View` struct to add some conditions to your original code.

**Comment by asakura42** [comment]
Thx, I'll try.

**Comment by asakura42** [comment]
Heh, I stucked in merging after last lib.rs editions... It seemed so simple but in fact I don't really know how to do it. I can start from scratch in couple days. But it seems to me that if you can do it in a couple of minutes, you better do it. I'm just learning the basics, anyway.

**Comment by lewis-weinberger** [comment]
> It seemed so simple but in fact I don't really know how to do it. I can start from scratch in couple days

Hi @asakura42, I've added the config options in bb25a98.

You can use these with your changes with something like this:
```rs
// in src/lib.rs, for impl View

if self.window.config.save_on_exit {
    // your code here
}

if self.window.config.print_priority {
    // your code here
}
```
I agree it might be easier to start again from bb25a98 rather than try to resolve the conflicts.

**Pull request closed without merging**
